export const barangays = [
    { id: 1, name: "Aplaya" },
    { id: 2, name: "Balabag" },
    { id: 3, name: "Binaton" },
    { id: 4, name: "Cogon" },
    { id: 5, name: "Dawis" },
    { id: 6, name: "Dulangan" },
    { id: 7, name: "Goma" },
    { id: 8, name: "Igpit" },
    { id: 9, name: "Kapatagan" },
    { id: 10, name: "Kiagot" },
    { id: 11, name: "Lungag" },
    { id: 12, name: "Mahayahay" },
    { id: 13, name: "Matti" },
    { id: 14, name: "Ruparan" },
    { id: 15, name: "San Agustin" },
    { id: 16, name: "San Jose" },
    { id: 17, name: "San Miguel" },
    { id: 18, name: "San Roque" },
    { id: 19, name: "Sinawilan" },
    { id: 20, name: "Soong" },
    { id: 21, name: "Tiguman" },
    { id: 22, name: "Tres de Mayo" },
    { id: 23, name: "Zone 1" },
    { id: 24, name: "Zone 2" },
    { id: 25, name: "Zone 3" },
];
