import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import Dropdown from "@/Components/Dropdown";
import ResponsiveNavLink from "@/Components/ResponsiveNavLink";
import { Link } from "@inertiajs/react";
import { LogOut, User2Icon } from "lucide-react";
import logo from "../Assets/logo.png";
export default function NavBar({ user }) {
    const [showingNavigationDropdown, setShowingNavigationDropdown] = useState(false);
    const [search, setSearch] = useState("");
    return (_jsxs("nav", { className: "fixed z-20 lg:[w-[1500px] bg-black", children: [_jsx("div", { className: "bg-white rounded-[1rem] max-w-screen-xl min-w-full shadow-sm mx-auto px-4 sm:px-6 lg:px-8", children: _jsxs("div", { className: "flex justify-between h-16", children: [_jsx("div", { className: "flex", children: _jsx("div", { className: "shrink-0 flex items-center", children: _jsx(Link, { href: "/dashboard", children: _jsx("div", { className: "w-full flex justify-center p-4", children: _jsx("img", { src: logo, alt: "logo", width: "200px" }) }) }) }) }), _jsx("div", { className: "content-center", children: _jsx("input", { type: "search", placeholder: "search", className: "p-4 py-2 w-500 h-10 rounded-[0.9rem] border-slate-300 outline-none focus:border-green-800 shadow-sm" }) }), _jsx("div", { className: "hidden sm:flex sm:items-center sm:ms-6", children: _jsx("div", { className: "ms-3 relative", children: _jsxs(Dropdown, { children: [_jsx(Dropdown.Trigger, { children: _jsx("span", { className: "inline-flex rounded-md", children: _jsxs("button", { type: "button", className: "inline-flex items-center px-3 py-2 border border-transparent text-sm leading-4 font-medium rounded-md text-gray-500 bg-white hover:text-gray-700 focus:outline-none transition ease-in-out duration-150", children: [_jsx("img", { src: user.pfp, width: "35px", height: "35px", className: "mr-1 rounded-lg" }), _jsx("span", { className: "mx-1 capitalize", children: user.firstname }), _jsx("span", { className: "capitalize", children: user.lastname }), _jsx("svg", { className: "ms-2 -me-0.5 h-4 w-4", xmlns: "http://www.w3.org/2000/svg", viewBox: "0 0 20 20", fill: "currentColor", children: _jsx("path", { fillRule: "evenodd", d: "M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z", clipRule: "evenodd" }) })] }) }) }), _jsxs(Dropdown.Content, { children: [_jsx(Dropdown.Link, { href: route("profile.edit"), className: "rounded-t-[2rem] ", children: _jsxs("div", { className: "flex gap-2", children: [_jsx(User2Icon, { size: 20 }), "Profile"] }) }), _jsx(Dropdown.Link, { href: route("logout"), method: "post", as: "button", className: "rounded-b-[2rem]", children: _jsxs("div", { className: "flex gap-2", children: [_jsx(LogOut, { size: 20 }), "Log Out"] }) })] })] }) }) }), _jsx("div", { className: "-me-2 flex items-center sm:hidden", children: _jsx("button", { onClick: () => setShowingNavigationDropdown((previousState) => !previousState), className: "inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out", children: _jsxs("svg", { className: "h-6 w-6", stroke: "currentColor", fill: "none", viewBox: "0 0 24 24", children: [_jsx("path", { className: !showingNavigationDropdown
                                                ? "inline-flex"
                                                : "hidden", strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M4 6h16M4 12h16M4 18h16" }), _jsx("path", { className: showingNavigationDropdown
                                                ? "inline-flex"
                                                : "hidden", strokeLinecap: "round", strokeLinejoin: "round", strokeWidth: "2", d: "M6 18L18 6M6 6l12 12" })] }) }) })] }) }), _jsxs("div", { className: (showingNavigationDropdown ? "block" : "hidden") +
                    " sm:hidden", children: [_jsx("div", { className: "pt-2 pb-3 space-y-1", children: _jsx(ResponsiveNavLink, { href: route("dashboard"), active: route().current("dashboard"), children: "Dashboard" }) }), _jsxs("div", { className: "pt-4 pb-1 border-t border-gray-200", children: [_jsxs("div", { className: "px-4", children: [_jsx("div", { className: "font-medium text-base text-gray-800", children: user.firstname }), _jsx("div", { className: "font-medium text-sm text-gray-500", children: user.email })] }), _jsxs("div", { className: "mt-3 space-y-1", children: [_jsx(ResponsiveNavLink, { href: route("profile.edit"), children: "Profile" }), _jsx(ResponsiveNavLink, { method: "post", href: route("logout"), as: "button", children: "Log Out" })] })] })] })] }));
}
